//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeVes.Bazaar.Client2.BasarComServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterResult", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.DataObjekts")]
    [System.SerializableAttribute()]
    public partial class ParameterResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrintPevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ProzSoldGeweinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SellerInfoTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrintPev {
            get {
                return this.PrintPevField;
            }
            set {
                if ((this.PrintPevField.Equals(value) != true)) {
                    this.PrintPevField = value;
                    this.RaisePropertyChanged("PrintPev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ProzSoldGewein {
            get {
                return this.ProzSoldGeweinField;
            }
            set {
                if ((this.ProzSoldGeweinField.Equals(value) != true)) {
                    this.ProzSoldGeweinField = value;
                    this.RaisePropertyChanged("ProzSoldGewein");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SellerInfoText {
            get {
                return this.SellerInfoTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SellerInfoTextField, value) != true)) {
                    this.SellerInfoTextField = value;
                    this.RaisePropertyChanged("SellerInfoText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizBase", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.Biz")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory))]
    public partial class BizBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizManufacturer", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.Biz")]
    [System.SerializableAttribute()]
    public partial class BizManufacturer : DeVes.Bazaar.Client2.BasarComServiceReference.BizBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizSupplierer", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.Biz")]
    [System.SerializableAttribute()]
    public partial class BizSupplierer : DeVes.Bazaar.Client2.BasarComServiceReference.BizBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMail01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone01Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReturnedToSupplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalutationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail01 {
            get {
                return this.EMail01Field;
            }
            set {
                if ((object.ReferenceEquals(this.EMail01Field, value) != true)) {
                    this.EMail01Field = value;
                    this.RaisePropertyChanged("EMail01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone01 {
            get {
                return this.Phone01Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone01Field, value) != true)) {
                    this.Phone01Field = value;
                    this.RaisePropertyChanged("Phone01");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReturnedToSupplier {
            get {
                return this.ReturnedToSupplierField;
            }
            set {
                if ((this.ReturnedToSupplierField.Equals(value) != true)) {
                    this.ReturnedToSupplierField = value;
                    this.RaisePropertyChanged("ReturnedToSupplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Salutation {
            get {
                return this.SalutationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalutationField, value) != true)) {
                    this.SalutationField = value;
                    this.RaisePropertyChanged("Salutation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierNo {
            get {
                return this.SupplierNoField;
            }
            set {
                if ((this.SupplierNoField.Equals(value) != true)) {
                    this.SupplierNoField = value;
                    this.RaisePropertyChanged("SupplierNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizPosition", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.Biz")]
    [System.SerializableAttribute()]
    public partial class BizPosition : DeVes.Bazaar.Client2.BasarComServiceReference.BizBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PriceMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReturnedToSupplierAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SoldAtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> SoldForField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SupplierIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastChange {
            get {
                return this.LastChangeField;
            }
            set {
                if ((this.LastChangeField.Equals(value) != true)) {
                    this.LastChangeField = value;
                    this.RaisePropertyChanged("LastChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Material {
            get {
                return this.MaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialField, value) != true)) {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Memo {
            get {
                return this.MemoField;
            }
            set {
                if ((object.ReferenceEquals(this.MemoField, value) != true)) {
                    this.MemoField = value;
                    this.RaisePropertyChanged("Memo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionNo {
            get {
                return this.PositionNoField;
            }
            set {
                if ((this.PositionNoField.Equals(value) != true)) {
                    this.PositionNoField = value;
                    this.RaisePropertyChanged("PositionNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceMax {
            get {
                return this.PriceMaxField;
            }
            set {
                if ((this.PriceMaxField.Equals(value) != true)) {
                    this.PriceMaxField = value;
                    this.RaisePropertyChanged("PriceMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> PriceMin {
            get {
                return this.PriceMinField;
            }
            set {
                if ((this.PriceMinField.Equals(value) != true)) {
                    this.PriceMinField = value;
                    this.RaisePropertyChanged("PriceMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReturnedToSupplierAt {
            get {
                return this.ReturnedToSupplierAtField;
            }
            set {
                if ((this.ReturnedToSupplierAtField.Equals(value) != true)) {
                    this.ReturnedToSupplierAtField = value;
                    this.RaisePropertyChanged("ReturnedToSupplierAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SoldAt {
            get {
                return this.SoldAtField;
            }
            set {
                if ((this.SoldAtField.Equals(value) != true)) {
                    this.SoldAtField = value;
                    this.RaisePropertyChanged("SoldAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> SoldFor {
            get {
                return this.SoldForField;
            }
            set {
                if ((this.SoldForField.Equals(value) != true)) {
                    this.SoldForField = value;
                    this.RaisePropertyChanged("SoldFor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BizMaterialCategory", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.Biz")]
    [System.SerializableAttribute()]
    public partial class BizMaterialCategory : DeVes.Bazaar.Client2.BasarComServiceReference.BizBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PositionSellResult", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.DataObjekts")]
    [System.SerializableAttribute()]
    public partial class PositionSellResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] NotPossibleToSellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeVes.Bazaar.Client2.BasarComServiceReference.PositionSellResult.NotSoldPosReasonTypes[] NotSoldPosReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] SoldPositionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] NotPossibleToSell {
            get {
                return this.NotPossibleToSellField;
            }
            set {
                if ((object.ReferenceEquals(this.NotPossibleToSellField, value) != true)) {
                    this.NotPossibleToSellField = value;
                    this.RaisePropertyChanged("NotPossibleToSell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeVes.Bazaar.Client2.BasarComServiceReference.PositionSellResult.NotSoldPosReasonTypes[] NotSoldPosReason {
            get {
                return this.NotSoldPosReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.NotSoldPosReasonField, value) != true)) {
                    this.NotSoldPosReasonField = value;
                    this.RaisePropertyChanged("NotSoldPosReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] SoldPositions {
            get {
                return this.SoldPositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SoldPositionsField, value) != true)) {
                    this.SoldPositionsField = value;
                    this.RaisePropertyChanged("SoldPositions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="PositionSellResult.NotSoldPosReasonTypes", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.DataObjekts")]
        public enum NotSoldPosReasonTypes : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MeanTimeChanged = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MeanTimeSold = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            MeanTimeReturned = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NotFound = 3,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PositionReturnedResult", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.DataObjekts")]
    [System.SerializableAttribute()]
    public partial class PositionReturnedResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] AlreadyReturnedPositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HadDifferencesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] NotSoldPositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionsCountTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PositionsToReturnCountTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PositionsToReturnMoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] SoldPositionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] AlreadyReturnedPositions {
            get {
                return this.AlreadyReturnedPositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.AlreadyReturnedPositionsField, value) != true)) {
                    this.AlreadyReturnedPositionsField = value;
                    this.RaisePropertyChanged("AlreadyReturnedPositions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HadDifferences {
            get {
                return this.HadDifferencesField;
            }
            set {
                if ((this.HadDifferencesField.Equals(value) != true)) {
                    this.HadDifferencesField = value;
                    this.RaisePropertyChanged("HadDifferences");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] NotSoldPositions {
            get {
                return this.NotSoldPositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.NotSoldPositionsField, value) != true)) {
                    this.NotSoldPositionsField = value;
                    this.RaisePropertyChanged("NotSoldPositions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionsCountTotal {
            get {
                return this.PositionsCountTotalField;
            }
            set {
                if ((this.PositionsCountTotalField.Equals(value) != true)) {
                    this.PositionsCountTotalField = value;
                    this.RaisePropertyChanged("PositionsCountTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PositionsToReturnCountTotal {
            get {
                return this.PositionsToReturnCountTotalField;
            }
            set {
                if ((this.PositionsToReturnCountTotalField.Equals(value) != true)) {
                    this.PositionsToReturnCountTotalField = value;
                    this.RaisePropertyChanged("PositionsToReturnCountTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PositionsToReturnMoney {
            get {
                return this.PositionsToReturnMoneyField;
            }
            set {
                if ((this.PositionsToReturnMoneyField.Equals(value) != true)) {
                    this.PositionsToReturnMoneyField = value;
                    this.RaisePropertyChanged("PositionsToReturnMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] SoldPositions {
            get {
                return this.SoldPositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SoldPositionsField, value) != true)) {
                    this.SoldPositionsField = value;
                    this.RaisePropertyChanged("SoldPositions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AllPositionResult", Namespace="http://schemas.datacontract.org/2004/07/DeVes.Bazaar.Data.DataObjekts")]
    [System.SerializableAttribute()]
    public partial class AllPositionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] PositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer SupplierField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] Positions {
            get {
                return this.PositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionsField, value) != true)) {
                    this.PositionsField = value;
                    this.RaisePropertyChanged("Positions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer Supplier {
            get {
                return this.SupplierField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierField, value) != true)) {
                    this.SupplierField = value;
                    this.RaisePropertyChanged("Supplier");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BasarComServiceReference.IBasarCom")]
    public interface IBasarCom {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/CheckAlive", ReplyAction="http://tempuri.org/IBasarCom/CheckAliveResponse")]
        string CheckAlive();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/CheckAlive", ReplyAction="http://tempuri.org/IBasarCom/CheckAliveResponse")]
        System.Threading.Tasks.Task<string> CheckAliveAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/GetParameters", ReplyAction="http://tempuri.org/IBasarCom/GetParametersResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.ParameterResult GetParameters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/GetParameters", ReplyAction="http://tempuri.org/IBasarCom/GetParametersResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.ParameterResult> GetParametersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryGet", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryGetResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory MaterialCategoryGet(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryGet", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryGetResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory> MaterialCategoryGetAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryGetAll", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryGetAllResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory[] MaterialCategoryGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryGetAll", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryGetAllResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory[]> MaterialCategoryGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryCreate", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryCreateResponse")]
        bool MaterialCategoryCreate(DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory materialCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryCreate", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryCreateResponse")]
        System.Threading.Tasks.Task<bool> MaterialCategoryCreateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory materialCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryUpdate", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryUpdateResponse")]
        bool MaterialCategoryUpdate(DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory materialCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryUpdate", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryUpdateResponse")]
        System.Threading.Tasks.Task<bool> MaterialCategoryUpdateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory materialCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryRemove", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryRemoveResponse")]
        bool MaterialCategoryRemove(System.Guid matlCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/MaterialCategoryRemove", ReplyAction="http://tempuri.org/IBasarCom/MaterialCategoryRemoveResponse")]
        System.Threading.Tasks.Task<bool> MaterialCategoryRemoveAsync(System.Guid matlCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerGet", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerGetResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer ManufacturerGet(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerGet", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerGetResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer> ManufacturerGetAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerGetAll", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerGetAllResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer[] ManufacturerGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerGetAll", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerGetAllResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer[]> ManufacturerGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerCreate", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerCreateResponse")]
        bool ManufacturerCreate(DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer manufacturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerCreate", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerCreateResponse")]
        System.Threading.Tasks.Task<bool> ManufacturerCreateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer manufacturer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerUpdate", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerUpdateResponse")]
        bool ManufacturerUpdate(DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer materialCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerUpdate", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerUpdateResponse")]
        System.Threading.Tasks.Task<bool> ManufacturerUpdateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer materialCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerRemove", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerRemoveResponse")]
        bool ManufacturerRemove(System.Guid matlCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/ManufacturerRemove", ReplyAction="http://tempuri.org/IBasarCom/ManufacturerRemoveResponse")]
        System.Threading.Tasks.Task<bool> ManufacturerRemoveAsync(System.Guid matlCatId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierGet_ByID", ReplyAction="http://tempuri.org/IBasarCom/SupplierGet_ByIDResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer SupplierGet_ByID(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierGet_ByID", ReplyAction="http://tempuri.org/IBasarCom/SupplierGet_ByIDResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer> SupplierGet_ByIDAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierGet_ByName", ReplyAction="http://tempuri.org/IBasarCom/SupplierGet_ByNameResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer SupplierGet_ByName(string supplierName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierGet_ByName", ReplyAction="http://tempuri.org/IBasarCom/SupplierGet_ByNameResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer> SupplierGet_ByNameAsync(string supplierName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierGet_No", ReplyAction="http://tempuri.org/IBasarCom/SupplierGet_NoResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer SupplierGet_No(int supplierNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierGet_No", ReplyAction="http://tempuri.org/IBasarCom/SupplierGet_NoResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer> SupplierGet_NoAsync(int supplierNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierGetAll", ReplyAction="http://tempuri.org/IBasarCom/SupplierGetAllResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer[] SupplierGetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierGetAll", ReplyAction="http://tempuri.org/IBasarCom/SupplierGetAllResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer[]> SupplierGetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierCreate", ReplyAction="http://tempuri.org/IBasarCom/SupplierCreateResponse")]
        System.Nullable<System.Guid> SupplierCreate(DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierCreate", ReplyAction="http://tempuri.org/IBasarCom/SupplierCreateResponse")]
        System.Threading.Tasks.Task<System.Nullable<System.Guid>> SupplierCreateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierUpdate", ReplyAction="http://tempuri.org/IBasarCom/SupplierUpdateResponse")]
        bool SupplierUpdate(DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierUpdate", ReplyAction="http://tempuri.org/IBasarCom/SupplierUpdateResponse")]
        System.Threading.Tasks.Task<bool> SupplierUpdateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierRemove", ReplyAction="http://tempuri.org/IBasarCom/SupplierRemoveResponse")]
        bool SupplierRemove(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SupplierRemove", ReplyAction="http://tempuri.org/IBasarCom/SupplierRemoveResponse")]
        System.Threading.Tasks.Task<bool> SupplierRemoveAsync(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SetSupplierToReturned", ReplyAction="http://tempuri.org/IBasarCom/SetSupplierToReturnedResponse")]
        bool SetSupplierToReturned(System.Nullable<System.Guid> supplierId, bool isReturned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SetSupplierToReturned", ReplyAction="http://tempuri.org/IBasarCom/SetSupplierToReturnedResponse")]
        System.Threading.Tasks.Task<bool> SetSupplierToReturnedAsync(System.Nullable<System.Guid> supplierId, bool isReturned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionCreate", ReplyAction="http://tempuri.org/IBasarCom/PositionCreateResponse")]
        bool PositionCreate(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition supplierPosition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionCreate", ReplyAction="http://tempuri.org/IBasarCom/PositionCreateResponse")]
        System.Threading.Tasks.Task<bool> PositionCreateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition supplierPosition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionUpdate", ReplyAction="http://tempuri.org/IBasarCom/PositionUpdateResponse")]
        bool PositionUpdate(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition supplierPosition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionUpdate", ReplyAction="http://tempuri.org/IBasarCom/PositionUpdateResponse")]
        System.Threading.Tasks.Task<bool> PositionUpdateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition supplierPosition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionRemove", ReplyAction="http://tempuri.org/IBasarCom/PositionRemoveResponse")]
        bool PositionRemove(int positionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionRemove", ReplyAction="http://tempuri.org/IBasarCom/PositionRemoveResponse")]
        System.Threading.Tasks.Task<bool> PositionRemoveAsync(int positionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionSell", ReplyAction="http://tempuri.org/IBasarCom/PositionSellResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.PositionSellResult PositionSell(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionSell", ReplyAction="http://tempuri.org/IBasarCom/PositionSellResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.PositionSellResult> PositionSellAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] position);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionReturn", ReplyAction="http://tempuri.org/IBasarCom/PositionReturnResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.PositionReturnedResult PositionReturn(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionReturn", ReplyAction="http://tempuri.org/IBasarCom/PositionReturnResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.PositionReturnedResult> PositionReturnAsync(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/GetSoldPositions", ReplyAction="http://tempuri.org/IBasarCom/GetSoldPositionsResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] GetSoldPositions(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/GetSoldPositions", ReplyAction="http://tempuri.org/IBasarCom/GetSoldPositionsResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[]> GetSoldPositionsAsync(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/GetSoldNotReturnedPositions", ReplyAction="http://tempuri.org/IBasarCom/GetSoldNotReturnedPositionsResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] GetSoldNotReturnedPositions(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/GetSoldNotReturnedPositions", ReplyAction="http://tempuri.org/IBasarCom/GetSoldNotReturnedPositionsResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[]> GetSoldNotReturnedPositionsAsync(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/GetNotSoldNotReturnedPositions", ReplyAction="http://tempuri.org/IBasarCom/GetNotSoldNotReturnedPositionsResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] GetNotSoldNotReturnedPositions(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/GetNotSoldNotReturnedPositions", ReplyAction="http://tempuri.org/IBasarCom/GetNotSoldNotReturnedPositionsResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[]> GetNotSoldNotReturnedPositionsAsync(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SetPositionsAsReturned", ReplyAction="http://tempuri.org/IBasarCom/SetPositionsAsReturnedResponse")]
        void SetPositionsAsReturned(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] positions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/SetPositionsAsReturned", ReplyAction="http://tempuri.org/IBasarCom/SetPositionsAsReturnedResponse")]
        System.Threading.Tasks.Task SetPositionsAsReturnedAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] positions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionGet", ReplyAction="http://tempuri.org/IBasarCom/PositionGetResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition PositionGet(int positionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionGet", ReplyAction="http://tempuri.org/IBasarCom/PositionGetResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition> PositionGetAsync(int positionNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionGetAll", ReplyAction="http://tempuri.org/IBasarCom/PositionGetAllResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] PositionGetAll(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/PositionGetAll", ReplyAction="http://tempuri.org/IBasarCom/PositionGetAllResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[]> PositionGetAllAsync(System.Guid supplierId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/AllSupplierAndPositions", ReplyAction="http://tempuri.org/IBasarCom/AllSupplierAndPositionsResponse")]
        DeVes.Bazaar.Client2.BasarComServiceReference.AllPositionResult[] AllSupplierAndPositions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBasarCom/AllSupplierAndPositions", ReplyAction="http://tempuri.org/IBasarCom/AllSupplierAndPositionsResponse")]
        System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.AllPositionResult[]> AllSupplierAndPositionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBasarComChannel : DeVes.Bazaar.Client2.BasarComServiceReference.IBasarCom, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BasarComClient : System.ServiceModel.ClientBase<DeVes.Bazaar.Client2.BasarComServiceReference.IBasarCom>, DeVes.Bazaar.Client2.BasarComServiceReference.IBasarCom {
        
        public BasarComClient() {
        }
        
        public BasarComClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BasarComClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasarComClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BasarComClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckAlive() {
            return base.Channel.CheckAlive();
        }
        
        public System.Threading.Tasks.Task<string> CheckAliveAsync() {
            return base.Channel.CheckAliveAsync();
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.ParameterResult GetParameters() {
            return base.Channel.GetParameters();
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.ParameterResult> GetParametersAsync() {
            return base.Channel.GetParametersAsync();
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory MaterialCategoryGet(System.Guid id) {
            return base.Channel.MaterialCategoryGet(id);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory> MaterialCategoryGetAsync(System.Guid id) {
            return base.Channel.MaterialCategoryGetAsync(id);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory[] MaterialCategoryGetAll() {
            return base.Channel.MaterialCategoryGetAll();
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory[]> MaterialCategoryGetAllAsync() {
            return base.Channel.MaterialCategoryGetAllAsync();
        }
        
        public bool MaterialCategoryCreate(DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory materialCategory) {
            return base.Channel.MaterialCategoryCreate(materialCategory);
        }
        
        public System.Threading.Tasks.Task<bool> MaterialCategoryCreateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory materialCategory) {
            return base.Channel.MaterialCategoryCreateAsync(materialCategory);
        }
        
        public bool MaterialCategoryUpdate(DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory materialCategory) {
            return base.Channel.MaterialCategoryUpdate(materialCategory);
        }
        
        public System.Threading.Tasks.Task<bool> MaterialCategoryUpdateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizMaterialCategory materialCategory) {
            return base.Channel.MaterialCategoryUpdateAsync(materialCategory);
        }
        
        public bool MaterialCategoryRemove(System.Guid matlCatId) {
            return base.Channel.MaterialCategoryRemove(matlCatId);
        }
        
        public System.Threading.Tasks.Task<bool> MaterialCategoryRemoveAsync(System.Guid matlCatId) {
            return base.Channel.MaterialCategoryRemoveAsync(matlCatId);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer ManufacturerGet(System.Guid id) {
            return base.Channel.ManufacturerGet(id);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer> ManufacturerGetAsync(System.Guid id) {
            return base.Channel.ManufacturerGetAsync(id);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer[] ManufacturerGetAll() {
            return base.Channel.ManufacturerGetAll();
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer[]> ManufacturerGetAllAsync() {
            return base.Channel.ManufacturerGetAllAsync();
        }
        
        public bool ManufacturerCreate(DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer manufacturer) {
            return base.Channel.ManufacturerCreate(manufacturer);
        }
        
        public System.Threading.Tasks.Task<bool> ManufacturerCreateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer manufacturer) {
            return base.Channel.ManufacturerCreateAsync(manufacturer);
        }
        
        public bool ManufacturerUpdate(DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer materialCategory) {
            return base.Channel.ManufacturerUpdate(materialCategory);
        }
        
        public System.Threading.Tasks.Task<bool> ManufacturerUpdateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizManufacturer materialCategory) {
            return base.Channel.ManufacturerUpdateAsync(materialCategory);
        }
        
        public bool ManufacturerRemove(System.Guid matlCatId) {
            return base.Channel.ManufacturerRemove(matlCatId);
        }
        
        public System.Threading.Tasks.Task<bool> ManufacturerRemoveAsync(System.Guid matlCatId) {
            return base.Channel.ManufacturerRemoveAsync(matlCatId);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer SupplierGet_ByID(System.Guid id) {
            return base.Channel.SupplierGet_ByID(id);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer> SupplierGet_ByIDAsync(System.Guid id) {
            return base.Channel.SupplierGet_ByIDAsync(id);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer SupplierGet_ByName(string supplierName) {
            return base.Channel.SupplierGet_ByName(supplierName);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer> SupplierGet_ByNameAsync(string supplierName) {
            return base.Channel.SupplierGet_ByNameAsync(supplierName);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer SupplierGet_No(int supplierNumber) {
            return base.Channel.SupplierGet_No(supplierNumber);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer> SupplierGet_NoAsync(int supplierNumber) {
            return base.Channel.SupplierGet_NoAsync(supplierNumber);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer[] SupplierGetAll() {
            return base.Channel.SupplierGetAll();
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer[]> SupplierGetAllAsync() {
            return base.Channel.SupplierGetAllAsync();
        }
        
        public System.Nullable<System.Guid> SupplierCreate(DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer supplier) {
            return base.Channel.SupplierCreate(supplier);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<System.Guid>> SupplierCreateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer supplier) {
            return base.Channel.SupplierCreateAsync(supplier);
        }
        
        public bool SupplierUpdate(DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer supplier) {
            return base.Channel.SupplierUpdate(supplier);
        }
        
        public System.Threading.Tasks.Task<bool> SupplierUpdateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizSupplierer supplier) {
            return base.Channel.SupplierUpdateAsync(supplier);
        }
        
        public bool SupplierRemove(System.Guid supplierId) {
            return base.Channel.SupplierRemove(supplierId);
        }
        
        public System.Threading.Tasks.Task<bool> SupplierRemoveAsync(System.Guid supplierId) {
            return base.Channel.SupplierRemoveAsync(supplierId);
        }
        
        public bool SetSupplierToReturned(System.Nullable<System.Guid> supplierId, bool isReturned) {
            return base.Channel.SetSupplierToReturned(supplierId, isReturned);
        }
        
        public System.Threading.Tasks.Task<bool> SetSupplierToReturnedAsync(System.Nullable<System.Guid> supplierId, bool isReturned) {
            return base.Channel.SetSupplierToReturnedAsync(supplierId, isReturned);
        }
        
        public bool PositionCreate(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition supplierPosition) {
            return base.Channel.PositionCreate(supplierPosition);
        }
        
        public System.Threading.Tasks.Task<bool> PositionCreateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition supplierPosition) {
            return base.Channel.PositionCreateAsync(supplierPosition);
        }
        
        public bool PositionUpdate(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition supplierPosition) {
            return base.Channel.PositionUpdate(supplierPosition);
        }
        
        public System.Threading.Tasks.Task<bool> PositionUpdateAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition supplierPosition) {
            return base.Channel.PositionUpdateAsync(supplierPosition);
        }
        
        public bool PositionRemove(int positionNo) {
            return base.Channel.PositionRemove(positionNo);
        }
        
        public System.Threading.Tasks.Task<bool> PositionRemoveAsync(int positionNo) {
            return base.Channel.PositionRemoveAsync(positionNo);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.PositionSellResult PositionSell(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] position) {
            return base.Channel.PositionSell(position);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.PositionSellResult> PositionSellAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] position) {
            return base.Channel.PositionSellAsync(position);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.PositionReturnedResult PositionReturn(System.Guid supplierId) {
            return base.Channel.PositionReturn(supplierId);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.PositionReturnedResult> PositionReturnAsync(System.Guid supplierId) {
            return base.Channel.PositionReturnAsync(supplierId);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] GetSoldPositions(System.Guid supplierId) {
            return base.Channel.GetSoldPositions(supplierId);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[]> GetSoldPositionsAsync(System.Guid supplierId) {
            return base.Channel.GetSoldPositionsAsync(supplierId);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] GetSoldNotReturnedPositions(System.Guid supplierId) {
            return base.Channel.GetSoldNotReturnedPositions(supplierId);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[]> GetSoldNotReturnedPositionsAsync(System.Guid supplierId) {
            return base.Channel.GetSoldNotReturnedPositionsAsync(supplierId);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] GetNotSoldNotReturnedPositions(System.Guid supplierId) {
            return base.Channel.GetNotSoldNotReturnedPositions(supplierId);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[]> GetNotSoldNotReturnedPositionsAsync(System.Guid supplierId) {
            return base.Channel.GetNotSoldNotReturnedPositionsAsync(supplierId);
        }
        
        public void SetPositionsAsReturned(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] positions) {
            base.Channel.SetPositionsAsReturned(positions);
        }
        
        public System.Threading.Tasks.Task SetPositionsAsReturnedAsync(DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] positions) {
            return base.Channel.SetPositionsAsReturnedAsync(positions);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition PositionGet(int positionNo) {
            return base.Channel.PositionGet(positionNo);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition> PositionGetAsync(int positionNo) {
            return base.Channel.PositionGetAsync(positionNo);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[] PositionGetAll(System.Guid supplierId) {
            return base.Channel.PositionGetAll(supplierId);
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.BizPosition[]> PositionGetAllAsync(System.Guid supplierId) {
            return base.Channel.PositionGetAllAsync(supplierId);
        }
        
        public DeVes.Bazaar.Client2.BasarComServiceReference.AllPositionResult[] AllSupplierAndPositions() {
            return base.Channel.AllSupplierAndPositions();
        }
        
        public System.Threading.Tasks.Task<DeVes.Bazaar.Client2.BasarComServiceReference.AllPositionResult[]> AllSupplierAndPositionsAsync() {
            return base.Channel.AllSupplierAndPositionsAsync();
        }
    }
}
