//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeVes.Bazaar.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int Number { get; set; }
        public int SupplierNumber { get; set; }
        public string MaterialName { get; set; }
        public string MaterialCategory { get; set; }
        public string MaterialManufacturer { get; set; }
        public Nullable<double> PriceMin { get; set; }
        public double PriceMax { get; set; }
        public string Memo { get; set; }
        public Nullable<double> SoldFor { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ChangedAt { get; set; }
        public Nullable<System.DateTime> ReturnedAt { get; set; }
        public Nullable<System.DateTime> SoldAt { get; set; }
    }
}
