//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeVes.Bazaar.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int Number { get; set; }
        public string Salutation { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Adress { get; set; }
        public string ZipCode { get; set; }
        public string Town { get; set; }
        public string Phone01 { get; set; }
        public string EMail01 { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ChangedAt { get; set; }
        public Nullable<System.DateTime> SoldOutAt { get; set; }
    }
}
